### ISSUE TITLE
Support for other PHP projects

### ISSUE THREAD

**Issue by LukeTowers** [facade/flare-client-php#14]
Are there any plans to add support for other PHP projects, specifically WordPress? One of the agencies that I work with has a few WordPress sites, and they're currently using Sentry to handle their error logs for Laravel, October CMS, & WordPress projects. 

I've been playing around with ignition (working on a plugin for October CMS right now, https://github.com/rainlab/ignition-plugin) and have liked what I've seen, so I'm wondering if there are any plans to expand and add support for WordPress. If there are, we would most likely move away from Sentry and switch to using Flare to manage our error logs.

**Comment by sschlein** [comment]
Hey @LukeTowers, you can track wordpress errors with Flare: https://flareapp.io/blog/4-track-wordpress-errors-with-flare

The same goes for every other PHP application.

:)
