### ISSUE TITLE
error composer update v1.6.1

### ISSUE THREAD

**Issue by stockhausen** [facade/flare-client-php#19]
Hello, 

i have this error when pass 1.6.0 to 1.6.1

PHP 7.3.27-9+ubuntu16.04

In Flare.php line 235:

Argument 1 passed to Facade\FlareClient\Flare::censorRequestBodyFields() mu
st be of the type array, null given, called in /var/www/XXXXX/vendo
r/facade/ignition/src/IgnitionServiceProvider.php on line 134

**Comment by anditsung** [comment]
Hi, i have the same issue. How to fix this?
