### ISSUE TITLE
Empty flare key still transmits errors

### ISSUE THREAD

**Issue by tpetry** [facade/flare-client-php#22]
On my development i "disabled" the flare error reporting by removing the flare key but still every exception is transmitted to flareapp.io. This is not something I would expect as it is transmitting many data (source code, database values) I did not consent to.

**Comment by freekmurze** [comment]
Our intention is not to transmit anything automatically when no key is provided.

Could you provide us with a demo app (or PHP script) where things are being transmitted to Flare when an API key isn't specified?

**Comment by tpetry** [comment]
```bash
git clone git@github.com:tpetry/flare-client-php-issue22.git
cd flare-client-php-issue22
composer install
php artisan error
```

The flare logger has been configured, but no api key is provided. You do see my dd statement printing the flare report when it's contacting the flare server. It seems somewhere is a check missing whether an api key was configured.

**Comment by freekmurze** [comment]
We'll continue the conversation in https://github.com/facade/ignition/pull/381
