### ISSUE TITLE
[Security] Workflow run-tests.yml is using vulnerable action shivammathur/setup-php

### ISSUE THREAD

**Issue by fockboi-lgtm** [facade/flare-client-php#28]
The workflow run-tests.yml is referencing action shivammathur/setup-php using references v1. However this reference is missing the commit [716331904ea2625d93a4f4f8f8c050d235845675](https://github.com/shivammathur/setup-php/commits/716331904ea2625d93a4f4f8f8c050d235845675) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by freekmurze** [comment]
Won't we get the current release using the current workflow?

Feel free to send a PR to propose a concrete change.
