### ISSUE TITLE
Crash in AddGitInformation middleware

### ISSUE THREAD

**Issue by olivernybroe** [facade/flare-client-php#32]
When I get an exception it crashes at the `AddGitInformation` middleware, resulting in me seeing another exception in the symfony error page instead.
![telegram-cloud-photo-size-4-5791989048104041545-y](https://user-images.githubusercontent.com/5870441/154080014-b7ad151b-4849-44a2-9e8c-2baa3385b678.jpg)

If I uncomment that middleware, it works and I can then see my original exception.
![telegram-cloud-photo-size-4-5791989048104041547-y](https://user-images.githubusercontent.com/5870441/154080123-e84878f5-2b4d-47b9-9be6-4e39f0a13e4f.jpg)

This happens on a completely new laravel repository installed via `composer create-project`, I do not have any remotes for the repository yet as it hasn't been commited.

**Comment by freekmurze** [comment]
This has been fixed in v1.0.2 of spatie/flare-client-php
