### ISSUE TITLE
Compatibility with symfony/http-foundation 6.x

### ISSUE THREAD

**Issue by deegital** [facade/flare-client-php#35]
Currently, it's not compatible with Laravel 9 and above (and other frameworks depending on the latest http-foundation) due to [dependency set to the max version of 5.x currently in the composer.json](https://github.com/facade/flare-client-php/blob/main/composer.json#L16).

**Comment by freekmurze** [comment]
This package is deprecated, take a look at spatie/flare-client-php for support for more modern Laravel apps.
